//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * The listen and listening types, new in Version 4.0, specify different ways that a score following or machine listening application can interact with a performer. The listen type handles interactions that are specific to a note. If multiple child elements of the same type are present, they should have distinct player and/or time-only attributes.
 * 
 * <p>Java class for listen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="listen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="assess" type="{}assess"/>
 *         &lt;element name="wait" type="{}wait"/>
 *         &lt;element name="other-listen" type="{}other-listening"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listen", propOrder = {
    "assessOrWaitOrOtherListen"
})
public class Listen {

    @XmlElements({
        @XmlElement(name = "assess", type = Assess.class),
        @XmlElement(name = "wait", type = Wait.class),
        @XmlElement(name = "other-listen", type = OtherListening.class)
    })
    protected List<Object> assessOrWaitOrOtherListen;

    /**
     * Gets the value of the assessOrWaitOrOtherListen property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assessOrWaitOrOtherListen property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssessOrWaitOrOtherListen().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Assess }
     * {@link Wait }
     * {@link OtherListening }
     * 
     * 
     */
    public List<Object> getAssessOrWaitOrOtherListen() {
        if (assessOrWaitOrOtherListen == null) {
            assessOrWaitOrOtherListen = new ArrayList<Object>();
        }
        return this.assessOrWaitOrOtherListen;
    }

}
