//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for numeral-mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="numeral-mode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="major"/>
 *     &lt;enumeration value="minor"/>
 *     &lt;enumeration value="natural minor"/>
 *     &lt;enumeration value="melodic minor"/>
 *     &lt;enumeration value="harmonic minor"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "numeral-mode")
@XmlEnum
public enum NumeralMode {

    @XmlEnumValue("major")
    MAJOR("major"),
    @XmlEnumValue("minor")
    MINOR("minor"),
    @XmlEnumValue("natural minor")
    NATURAL_MINOR("natural minor"),
    @XmlEnumValue("melodic minor")
    MELODIC_MINOR("melodic minor"),
    @XmlEnumValue("harmonic minor")
    HARMONIC_MINOR("harmonic minor");
    private final java.lang.String value;

    NumeralMode(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static NumeralMode fromValue(java.lang.String v) {
        for (NumeralMode c: NumeralMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
