//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pedal-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pedal-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="start"/>
 *     &lt;enumeration value="stop"/>
 *     &lt;enumeration value="sostenuto"/>
 *     &lt;enumeration value="change"/>
 *     &lt;enumeration value="continue"/>
 *     &lt;enumeration value="discontinue"/>
 *     &lt;enumeration value="resume"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pedal-type")
@XmlEnum
public enum PedalType {

    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("stop")
    STOP("stop"),
    @XmlEnumValue("sostenuto")
    SOSTENUTO("sostenuto"),
    @XmlEnumValue("change")
    CHANGE("change"),
    @XmlEnumValue("continue")
    CONTINUE("continue"),
    @XmlEnumValue("discontinue")
    DISCONTINUE("discontinue"),
    @XmlEnumValue("resume")
    RESUME("resume");
    private final java.lang.String value;

    PedalType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PedalType fromValue(java.lang.String v) {
        for (PedalType c: PedalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
