//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sync-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="sync-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="tempo"/>
 *     &lt;enumeration value="mostly-tempo"/>
 *     &lt;enumeration value="mostly-event"/>
 *     &lt;enumeration value="event"/>
 *     &lt;enumeration value="always-event"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "sync-type")
@XmlEnum
public enum SyncType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("tempo")
    TEMPO("tempo"),
    @XmlEnumValue("mostly-tempo")
    MOSTLY_TEMPO("mostly-tempo"),
    @XmlEnumValue("mostly-event")
    MOSTLY_EVENT("mostly-event"),
    @XmlEnumValue("event")
    EVENT("event"),
    @XmlEnumValue("always-event")
    ALWAYS_EVENT("always-event");
    private final java.lang.String value;

    SyncType(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SyncType fromValue(java.lang.String v) {
        for (SyncType c: SyncType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
