//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for system-relation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="system-relation">
 *   &lt;restriction base="{}system-relation-number">
 *     &lt;enumeration value="only-top"/>
 *     &lt;enumeration value="also-top"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "system-relation")
@XmlEnum(SystemRelationNumber.class)
public enum SystemRelation {

    @XmlEnumValue("only-top")
    ONLY_TOP(SystemRelationNumber.ONLY_TOP),
    @XmlEnumValue("also-top")
    ALSO_TOP(SystemRelationNumber.ALSO_TOP),
    @XmlEnumValue("none")
    NONE(SystemRelationNumber.NONE);
    private final SystemRelationNumber value;

    SystemRelation(SystemRelationNumber v) {
        value = v;
    }

    public SystemRelationNumber value() {
        return value;
    }

    public static SystemRelation fromValue(SystemRelationNumber v) {
        for (SystemRelation c: SystemRelation.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
