//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The numeral-key type is used when the key for the numeral is different than the key specified by the key signature. The numeral-fifths element specifies the key in the same way as the fifths element. The numeral-mode element specifies the mode similar to the mode element, but with a restricted set of values
 * 
 * <p>Java class for numeral-key complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="numeral-key">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeral-fifths" type="{}fifths"/>
 *         &lt;element name="numeral-mode" type="{}numeral-mode"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}print-object"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "numeral-key", propOrder = {
    "numeralFifths",
    "numeralMode"
})
public class NumeralKey {

    @XmlElement(name = "numeral-fifths", required = true)
    protected BigInteger numeralFifths;
    @XmlElement(name = "numeral-mode", required = true)
    @XmlSchemaType(name = "string")
    protected NumeralMode numeralMode;
    @XmlAttribute(name = "print-object")
    protected YesNo printObject;

    /**
     * Gets the value of the numeralFifths property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumeralFifths() {
        return numeralFifths;
    }

    /**
     * Sets the value of the numeralFifths property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeralFifths(BigInteger value) {
        this.numeralFifths = value;
    }

    /**
     * Gets the value of the numeralMode property.
     * 
     * @return
     *     possible object is
     *     {@link NumeralMode }
     *     
     */
    public NumeralMode getNumeralMode() {
        return numeralMode;
    }

    /**
     * Sets the value of the numeralMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumeralMode }
     *     
     */
    public void setNumeralMode(NumeralMode value) {
        this.numeralMode = value;
    }

    /**
     * Gets the value of the printObject property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getPrintObject() {
        return printObject;
    }

    /**
     * Sets the value of the printObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setPrintObject(YesNo value) {
        this.printObject = value;
    }

}
