//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.18 at 09:23:50 PM EST 
//


package org.musicxml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for system-relation-number.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="system-relation-number">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="only-top"/>
 *     &lt;enumeration value="only-bottom"/>
 *     &lt;enumeration value="also-top"/>
 *     &lt;enumeration value="also-bottom"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "system-relation-number")
@XmlEnum
public enum SystemRelationNumber {

    @XmlEnumValue("only-top")
    ONLY_TOP("only-top"),
    @XmlEnumValue("only-bottom")
    ONLY_BOTTOM("only-bottom"),
    @XmlEnumValue("also-top")
    ALSO_TOP("also-top"),
    @XmlEnumValue("also-bottom")
    ALSO_BOTTOM("also-bottom"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    SystemRelationNumber(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SystemRelationNumber fromValue(java.lang.String v) {
        for (SystemRelationNumber c: SystemRelationNumber.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
